name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-test:
    name: "Deploy test"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Deploy
        run: bash scripts/deploy.sh
        env:
          HOSTING_API_SECRET: ${{ secrets.HOSTING_API_SECRET }}
          HOSTING_API_URL: ${{ secrets.HOSTING_API_URL }}
          HOSTING_ENV: test
